# Generated by Django 3.2.13 on 2023-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_claim_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='proof_doc',
            field=models.FileField(upload_to='proofs/'),
        ),
    ]
